name: chrome_style_browser_lego
description: "Chrome Style Browser View Lego"
#publish_to: 'none'
#repository: https://github.com/melodysdreamj/lego

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: #@add
  gap: #@add
  june_flow_util:
  styled_widget: #@add
  modal_bottom_sheet: #@add
  keyboard_attachable: #@add
  flutter_zoom_drawer: #@add
  flutter_screenutil:
  bot_toast:
  flutter_inappwebview: #@add
  super_cupertino_navigation_bar:
    git:
      url: https://github.com/melodysdreamj/super_cupertino_navigation_bar

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  screenutil_lego: #@add
  bot_toast_lego: #@add
  theme_config_lego: #@add

flutter:
  assets:
    - assets/lego/chrome_style_browser_lego/
  uses-material-design: true

topics:
  - lego